
# http://forum.mrmoneymustache.com/investor-alley/i-think-we-have-two-much-in-our-401ks

startage = 50

[prep]
workyears = 3
maxsave = 40000     # pre-tax dollars to save each year
tax_rate = 33

[IRA]
bal = 840000
maxcontrib = 40000  # over 50 401k + 401k

[income.social_sec]
amount = 40000
age = "70-"
inflation = true
tax = true
